## docker-compose.yml

# 도커 컨테이너 관리
# 이미지 관리를 도와줌
# 이 파일은 개발용으로 사용 DEV=true로 바뀌면서 flake8 설치
# deploy.yml 는 배포용으로 사용
# 장고는 8000 포트를 사용하니까 우리도 8000 포트
# 우리의 8000포트는 컨테이너의 8000 포트로 맵핑
# volumes:저장공간 루트폴더의 app:가상환경 app
# Command : 0.0.0.0 모든 아이피 주소에서 8000포트로 접근 가능 127.0.0.1은 로컬에서만 가능하도록 설정
# 도커 컴포즈 파일을 빌드 : docker-compose build

version: "3.11"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      # 디비 연결 먼저하고 서버 켜
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment: # .env는 커밋X 회사에서는 onepassword 프로그램을 사용해 .env 파일을 직접 만들어야됨
      - DB_HOST=db
      # postgres env랑 동일하게
      - DB_NAME=youtube
      - DB_USER=hotbari
      - DB_PASS=password123

    depends_on: # 장고에서 db가 연결이 안되어있으면 장고가 터지기 때문에 db컨테이너 실행 후 앱 실행
      - db

  # 두번째 컨테이너 : Postgres
  db:
    image: postgres:16-alpine
    volumes: # DB는 데이터 저장 공간이 필요해
      - ./data/db:/var/lib/postgresql/data # 로컬 공간 data폴더의 db(호스트 공간)를 : 이하(컨테이너 폴더)로 마운트
    environment: # 접근 권한에 대한 환경 변수
      - POSTGRES_DB=youtube
      - POSTGRES_USER=hotbari
      - POSTGRES_PASSWORD=password123